### ISSUE TITLE
Cannot find module './db.json'

### ISSUE THREAD

**Issue by xia-fei** [huweihuang/hexo-theme-huweihuang#6]
大家都没遇到这个错吗？
```
C:\Users\XiaFei\Desktop\blog\hexo-huweihuang>hexo clean
(node:13996) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
ERROR Plugin load failed: hexo-server
Error: Cannot find module './db.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\XiaFei\Desktop\blog\hexo-huweihuang\node_modules\mime-db\index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\XiaFei\Desktop\blog\hexo-huweihuang\node_modules\mime-types\index.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\XiaFei\Desktop\blog\hexo-huweihuang\node_modules\accepts\index.js:16:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by Luhangh** [comment]
一样的问题  怎么解决呢

**Comment by huweihuang** [comment]
试下 hexo clean的命令，清除掉缓存，然后重新生成，hexo g, hexo server
